Open-Science-Community-Saudi-Arabia/MOOCs

backend_API/src/models/password.models.js
backend_API/src/models/user.models.js

Added database schema models for users and admins including their passwords
Fixes #30 
* *Add schema models for end users and admins*
* *Add password models for admin and end users*

[15/10/2022]: Backend API [feat] - users db model

---

backend_API/src/app.js
backend_API/src/middlewares/error_handler.js
backend_API/src/routes/routes_handler.js
backend_API/src/utils/async_wrapper.js
backend_API/src/utils/custom_errors.js

Async function wrappers to abstract try catch block in controller functions.
Including custom error utility and error handler middlewares
Fixes #33
* *Added error handler middleware*
* *Added custom error utility*
* *Added async function wrapper*

[15/10/2022]: Backend API [feat] - async function wrappers and error handlers

---

backend_API/package-lock.json
backend_API/package.json
backend_API/src/controllers/auth.controllers.js
backend_API/src/routes/auth.routes.js
backend_API/src/utils/config.js

Added social sign in feature with google to backend API
Fixes #48
* *Add social signin with google*

[18/10/2022]: Backend API [feat] - Social signin with Google 

---

.gitignore
backend_API/package-lock.json
backend_API/package.json
backend_API/src/app.js
backend_API/src/controllers/auth.controllers.js
backend_API/src/db/connectDB.js
backend_API/src/models/category.models.js
backend_API/src/models/course.models.js
backend_API/src/models/user.models.js
backend_API/src/routes/course.routes.js
backend_API/src/server.js
backend_API/src/test/0database.test.js
backend_API/src/test/auth.test.js
backend_API/src/utils/config.js

Reverts Open-Science-Community-Saudi-Arabia/MOOCs#78

Revert "Revert "[21/10/2022] : Backend API [feat] - Unit tests ""

---

backend_API/src/controllers/auth.controllers.js
backend_API/src/middlewares/auth.js
backend_API/src/models/test_token.models.js
backend_API/src/models/user.models.js
backend_API/src/routes/auth.routes.js
backend_API/src/test/auth.test.js

Add email verification feature to backend API, should be triggered after each new signup
Fixes #91
* *Send email verification link to users email*
* *Verify users email account*
* *Add route and controller for user email verification*
* *Add check in auth middleware to restrict requests made to protected routes from unverified accounts*

[26/10/2022]: Backend API [feat] - Verify email

---

backend_API/src/controllers/courses.controller.js
backend_API/src/models/course.models.js
backend_API/src/routes/course.routes.js

Add update course feature for backend API for MOOCs platform
Fixes #95
Add routes and controllers for
* *Add update course feature*

[27/10/2022] Backend API [feat] - Update course

---

backend_API/src/controllers/course.controllers.js

Sub issue from #5 
Update GET /course data to account for other queries in backend API
Fixes #102
Add queries for

[27/10/2022]: Backend API [feat] - Get data for course

---

backend_API/src/controllers/exercise.controllers.js
backend_API/src/controllers/question.controllers.js
backend_API/src/models/course.models.js
backend_API/src/routes/course.routes.js
backend_API/src/routes/exercise.routes.js
backend_API/src/routes/question.routes.js
backend_API/src/routes/routes_handler.js

Add CRUD operation features for questions in exercises (for backend API)
Fixes #98
Added routes and controllers for

[29/10/2022] Backend API [feat] - CRUD for questions

---

backend_API/package.json
backend_API/src/controllers/auth.controllers.js
backend_API/src/controllers/course.controllers.js
backend_API/src/controllers/question.controllers.js
backend_API/src/middlewares/permission_handler.js
backend_API/src/routes/course.routes.js
backend_API/src/routes/exercise.routes.js
backend_API/src/test/auth.test.js

When running the unit test for the Authentication controls and routes it shows
Fixes #108
* *Fix unit test for authentication*
* *Update missing imports*

[31/10/2022] Backend API [fix] - Failed authentication test

---

backend_API/src/controllers/course.controllers.js
backend_API/src/models/course.models.js
backend_API/src/models/user.models.js
backend_API/src/routes/course.routes.js

Add enroll course feature and cancel course enrollment feature to backend API
Fixes #107

[01/11/2022] Backend API [feat]: Enrolled course

---

backend_API/src/API doc/MOOCs.postman_collection.json

Added postman API documentation for Authentication routes
Addresses (but does not close) #105
* *API documentation for Authentication routes /login, /signup, /verifyemail, /forgotpassword, /resetpassword*

[01/11/2022] Backend API [feat] - API documentation for AUTH routes

---

backend_API/package-lock.json
backend_API/package.json

While trying to deploy the backend API on render, it displayed a `MODULE NOT FOUND` error
Fixes #114

[11/07/2022] Backend API - Add cloudinary to dependencies 

---

Frontend/src/components/Button/Button.jsx
Frontend/src/pages/auth/forgotpassword/index.jsx
Frontend/src/pages/auth/forgotpassword/style.scss
Frontend/src/pages/auth/login/index.jsx
Frontend/src/pages/auth/signup/index.jsx
Frontend/src/pages/auth/style.scss
Frontend/src/styles/GlobalStyles.scss
Frontend/src/styles/_mixins.scss

Fixes issue: https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/130
This PR includes
- refactoring the login  , sign up  and forgot password SCSS files.

refactor css to scss

---

backend_API/src/controllers/auth.controllers.js
backend_API/src/utils/auth_codes.js

Password reset code sent to users email was showing undefined
Fixes #137 
* *Add proper value for password reset code*

[01/12/2022] Fix: undefined password reset code in users email

---

backend_API/src/app.js
backend_API/src/controllers/auth.controllers.js
backend_API/src/middlewares/auth.js
backend_API/src/models/token.models.js
backend_API/src/models/user.models.js
backend_API/src/utils/auth_codes.js
backend_API/src/utils/custom_errors.js

After initiating password reset, users can't login with the new password.
Users can reset their passwords repeatedly with the same access token and password reset code. It should be a one time access per access token.
Fixes #139
*Lorem ipsum dolor sit amet, consectetur adipiscing.*
* *Saved new hash of password to db*
* *Implemented blacklisted tokens to revoke JWT token used to initiate password reset flow*

[02/12/2022] - Fix: New password not logging in

---

backend_API/src/controllers/auth.controllers.js
backend_API/src/controllers/course.controllers.js
backend_API/src/controllers/exercise.controllers.js
backend_API/src/controllers/question.controllers.js
backend_API/src/utils/auth_codes.js
backend_API/src/utils/email.js
backend_API/src/utils/jwt_handler.js

Added code documentation for functions and controllers 
Fixes #143
*Lorem ipsum dolor sit amet, consectetur adipiscing.*
Added documentation for
- Auth controllers
- Utility functions
- Course, Exercise, and Question controllers

[23/12/2022] - Add code documentation

---

CHANGELOG.md

Updated changelog with new features for
- Code documentation for backend src code [#150](https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/150)
- Implemented signin with google and github [#153](https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/153)
* *Updated changelog*

changelog: added signin with google and github

---

CHANGELOG.md

PR Description
To keep track of features and changes, I have updated the changelog.MD file to reflect recent changes.
Recent changes include
- Added JsDoc pages for deployment, deployment [link](https://moocs-jsdocs.netlify.app/)  #157
-Added Code documentation using JsDocs #155

[13/01/2023]: Update CHANGELOG.md

---

CHANGELOG.md

Update changelog to include changes in API for
- Improved login, signup auth flow, access token management [#166](https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/166)
- Add superAdmin authentication, activateAccount, deactivateAccount feature for superadmin and user [#170](https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/170)

[24/01/2023] Update changelog for PR#166 and PR#170

---

CHANGELOG.md

Add dates to logs in CHANGELOG.md file

[24/01/2023] - add dates to logs in CHANGELOG.md

---

.github/workflows/weekly_pr_from_dev_to_main.yml

Fixes #<NUM>
*Lorem ipsum dolor sit amet, consectetur adipiscing.*
* *Lorem ipsum dolor sit amet, consectetur adipiscing.*
* *Lorem ipsum dolor sit amet, consectetur adipiscing.*

uncomment workflow file

---

backend_API/src/controllers/auth.controllers.js
backend_API/src/middlewares/auth.js
backend_API/src/middlewares/error_handler.js
backend_API/src/middlewares/permission_handler.js
backend_API/src/models/token.models.js
backend_API/src/models/user.models.js
backend_API/src/routes/auth.routes.js
backend_API/src/utils/token.js

Review auth API controllers and features
*Lorem ipsum dolor sit amet, consectetur adipiscing.*
* *Fix auth controlloers*
* *Update API documentation*

[28/01/2023] fix: auth API

---

CHANGELOG.md

Updated changelog to include
- #181 
- #180 
- #182

[06/02/2023] Update changelog

---

.github/workflows/auto_pr_dev_to_main.yml

Corrects the title of scheduled PR from `dev` to `main` branch
Fixes #186

[06/02/2023] fix: title of scheduled PR from `dev` to `main` branch

---

documentation/jsdoc.json

When deploying the docs to [railway](https://railway.app), i encountered this error
* *remove line to include src folder in `/backend_API` and `/Frontend` folders**

[08/02/2023] fix: unable to find sourcefile - jsdoc.json

---

documentation/server.js

Hosted docs server cant access $PORT variable
* *Switch documentation server to express server*

[08/02/2023] switch doc server to express - documentation/server.js

---

documentation/jsdoc.json
documentation/package-lock.json
documentation/package.json
documentation/server.js

Documentation shows `cannot get` ERROR when deployed to railway.app
* *Update JSDOC config to include source files from `backend_API` and `Frontend` folders*

[20/02/2023] fix: documentation deployment

---

CHANGELOG.md

Updated changelog to include
- PR #184
- PR #186
- PR #188
- PR #190
- PR #196

[20/02/2023] - Update changelog

---

API/src/models/password.models.js
API/src/models/user.models.js
API/src/test/0database.test.js
API/src/test/auth.test.js
API/src/utils/passport.js

Update test suites for Authentication API
Partially fixes #200
Contd from #201
* *Add code comments*
* *Improve test suites for `/forgotpassword` `/resetpassword` routes and controllers*

[24/02/2023] Unit tests - Authentication

---

API/src/controllers/auth.controllers.js
API/src/middlewares/auth.js
API/src/middlewares/error_handler.js
API/src/models/token.models.js
API/src/routes/course.routes.js
API/src/server.js
API/src/test/0database.test.js
API/src/test/auth.test.js
API/src/utils/token.js

Update test suites for Authentication API
Partially fixes #200
Contd from #204
* *Add code comments*
* *Improve test suites for `/forgotpassword` `/resetpassword` routes and controllers*

Unit test - `/verifyemail`

---

CHANGELOG.md

Updated changelog to include
- PR #201
- PR #204

[26/02/2023] Update changelog

---

.github/workflows/auto_pr_backend_dev_to_dev.yml
.github/workflows/auto_pr_frontend_dev_to_dev.yml

For the automated PR's, the source branch in the PR title didn't match the real branch names
* *Fix mismatch in branch names .*

[26/02/2023] fix: mismatch in branch name for automated PR title 

---

.github/workflows/auto_pr_backend_dev_to_dev.yml
.github/workflows/auto_pr_dev_to_main.yml
.github/workflows/auto_pr_frontend_dev_to_dev.yml

Add PR message for automated PRs, switched from using default PR template
* *add: PR message for automated PR's*

[26/02/2023] add: PR message for automated PR's - workflow

---

API/src/server.js

[02/03/2023] set API environments

---

API/src/controllers/course.controllers.js
API/src/controllers/exercise.controllers.js
API/src/controllers/question.controllers.js
API/src/models/course.models.js
API/src/routes/course.routes.js
API/src/routes/exercise.routes.js
API/src/routes/question.routes.js

Update quizzes / exercise in course content
* *Test features for exercises and questions*
* *Update API doc for exercise and questions*

[04/03/2023] Update exercise and question features

---

API/src/controllers/exercise.controllers.js
API/src/controllers/question.controllers.js
API/src/models/course.models.js
API/src/routes/exercise.routes.js

Add feature to score exercises
Users should have a record of their previous grades
* *Improve the `scoreExercise` feature*
* *Add feature to save users grades*
* *Model for exercise submission record*
* *Add get previous quiz result feature*
* *Add get quiz result data*

[05/03/2023] feat: Score Exercises

---

API/src/controllers/course.controllers.js
API/src/controllers/exercise.controllers.js
API/src/models/user.models.js
API/src/routes/course.routes.js

Add a feature to allow users to enroll for courses and cancel course enrollment,
Only enrolled users should be  allowed to take exercises within the course
* *Add enrollCourse, cancelEnrollment, getEnrolledCourses, getEnrolledUsers*
* *Restrict quizzes to only enrolled users*

[06/03/2023] feat: enrollCourse, cancelEnrollment

---

API/src/controllers/auth.controllers.js
API/src/controllers/question.controllers.js
API/src/models/course.models.js

The quiz option datatype was originally a Map() where the keys are a range of consecutive letters from A - Z and the values are the options for the quiz question.
```js
options: {
type: Map,
of: String,
enum: arrayOfCapitalLetters(),
required: true
}
```
With this structure, it wont be flexible to shuffle the order of the options on the frontend. A better alternative is to use an array of strings instead, this way it'll be easier to change the order on the frontend
* *Change question options data type to array of strings*
* *Update createQuestion and scoreExercise to accommodate this new datatype*

[08/03/2023] Update quiz options datatype

---

API/src/controllers/coursesection.controllers.js
API/src/models/course.models.js
API/src/routes/coursesection.routes.js
API/src/routes/routes_handler.js

Add sections for courses, these sections should contain videos and exercises
Fixes #233
* *Add section model and relate them to the courses models*
* *CRUD operations for course sections*

[10/03/2023] feat: Course sections

---

API/src/controllers/course.controllers.js
API/src/controllers/coursesection.controllers.js
API/src/controllers/exercise.controllers.js
API/src/models/course.models.js
API/src/routes/course.routes.js
API/src/routes/coursesection.routes.js

Improve on the course sections
Fixes #234

[11/03/2023] Improve CourseSections

---

.github/workflows/automated_tests.yml
API/src/controllers/auth.controllers.js
API/src/controllers/course.controllers.js
API/src/controllers/exercise.controllers.js
API/src/models/course.models.js
API/src/routes/course.routes.js
API/src/utils/passport.js

Reverts Open-Science-Community-Saudi-Arabia/MOOCs#246

Revert "[14/03/2023] Combine course contents into one array"

---

API/src/controllers/course.controllers.js
API/src/controllers/exercise.controllers.js
API/src/models/course.models.js

This PR adds a feature to track if a user has completed an exercise
* *Add isCompleted status to all exercises when user makes request to get course data*

[22/03/2023] feat: Exercise tracking

---

API/src/controllers/course.controllers.js
API/src/controllers/exercise.controllers.js
API/src/middlewares/auth.js
API/src/models/course.models.js
API/src/routes/course.routes.js
API/src/routes/exercise.routes.js

Issues:
- The GET /course and /courses query doesn't return the question in the course exercises
- Update benchmark for passing course
- Each exercise should carry a field to know the best score the user had
- Added questions to returned response for GET /course and /courses
- Added exercise report schema
- Added feature to track if an exercise has been completed
- Added benchmark to pass an exercise

[25/03/2023]: update: getCourse response, and scoreExercise

---

API/package-lock.json
API/package.json
API/src/controllers/course.controllers.js
API/src/utils/cloudinary.js
API/src/utils/config.js
API/src/utils/crowdin.js

This PR adds support to translate the API response before sending to the client app
* *Add crowdin API integration to MOOCs API*
* *Create middleware for translation*

[11-04-2023] Translate API response

---

API/src/controllers/course.controllers.js
API/src/controllers/coursesection.controllers.js
API/src/controllers/downloadableresources.controllers.js
API/src/controllers/exercise.controllers.js
API/src/controllers/question.controllers.js
API/src/controllers/textmaterial.controllers.js
API/src/models/course.models.js
API/src/server.js
API/src/utils/crowdin.js

This PR aims to improve the time it takes to complete the translation process when the courses are being created.
Partially fixes #292
- Improve localization speed
- Initiate localization on course creation.

[07/05/2023] Update localisation feat on backend to improve speed

---

API/src/utils/crowdin.js

The translation for other documents works well, but throws an error while carrying our translation for questions
Partially fixes #294
- Fix translation for questions

[08/05/2023] fix: translation for questions

---

API/src/controllers/course.controllers.js

:crown: *An automated PR*
Weekly automated PR from `backend_dev` to `dev` branch
_Created by [repo-sync/pull-request](https://github.com/repo-sync/pull-request)_

Weekly auto PR from `backend_dev` into `dev` branch

---

.github/workflows/merge_crowdin.yml

PR DESCRIPTION
Fixes issue #322

Github action to automate translation compilation

---

.github/workflows/merge_crowdin.yml
client/.gitignore
client/src/App.tsx
client/src/components/Footer/index.tsx
client/src/pages/auth/login/index.tsx
client/src/pages/auth/signup/index.tsx
client/src/pages/auth/style.scss

fixed styling and Arabic view

---

client/package.json
client/postcss.config.js
client/src/App.tsx
client/src/components/DashboardHeader/index.tsx
client/src/components/DashboardHeader/style.scss
client/src/main.tsx
client/src/pages/admin/index.tsx
client/src/pages/auth/admin/index.tsx
client/src/pages/auth/admin/login.tsx
client/src/pages/auth/login/index.tsx
client/src/pages/auth/signup/index.tsx
client/src/pages/auth/style.scss
client/src/pages/auth/verification-link/index.tsx
client/src/pages/board/dashboard/index.tsx
client/src/pages/collaborator/index.tsx
client/src/styles/GlobalStyles.scss
client/src/types/index.tsx
client/tailwind.config.js
client/yarn.lock

PR description
Added the required sign up page for Collaborator and user.
Fixes issue: https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/329

Auth pages for collaborator and user.

---

API/src/controllers/course.js
API/src/models/course.js
API/src/models/course.models.js
API/src/routes/course.js
API/src/routes/course.routes.js
API/src/routes/routes_handler.js
API/src/services/course.js

Fixes: #329
PR Description
- Create new API for adding course
- Create a database scheme
- Create a controller and services

Feature:Created model and controller for creating new course

---

API/src/controllers/course.js
API/src/models/course.js
API/src/routes/course.js
API/src/services/course.js
client/src/components/AddCourse/NestedArray.tsx
client/src/components/AddCourse/index.tsx
client/src/utils/index.ts

Fixes: #329
PR Description
- Added endpoints for collaborator , user and Admin

Chore:updated collaborator endpoints

---

API/src/controllers/course.js
API/src/middlewares/permission_handler.js
API/src/models/user.models.js
API/src/routes/course.js
API/src/services/course.js
client/src/App.tsx
client/src/components/Layouts/dashboard.tsx
client/src/hooks/useFetch.tsx
client/src/pages/auth/login/index.tsx
client/src/pages/auth/signup/index.tsx
client/src/pages/board/dashboard/availablecourses/index.tsx
client/src/pages/board/dashboard/availablecourses/style.scss
client/src/pages/board/dashboard/index.tsx
client/src/pages/board/dashboard/style.scss
client/src/pages/contributor/index.tsx
client/src/pages/contributor/style.scss
client/src/utils/api/courses.ts

Fixes:Issue #329
PR Description
- Rename Collaborator to contributor
- added getAll approved courses for end-user

Chore:Rename collaborator to contributor

---

API/src/controllers/course.js
API/src/models/user.models.js
API/src/routes/course.js
API/src/services/course.js
client/src/components/Course/Table.tsx
client/src/hooks/useFetch.tsx
client/src/pages/board/dashboard/availablecourses/index.tsx
client/src/pages/board/dashboard/availablecourses/style.scss
client/src/pages/board/viewcourse/ExerciseQuiz.tsx
client/src/pages/board/viewcourse/index.tsx
client/src/pages/board/viewcourse/style.scss
client/src/pages/contributor/index.tsx
client/src/types/index.tsx
client/src/utils/api/courses.ts
client/tailwind.config.js

Fixes: #329 
PR Description
- Updated Course page for user
- user can enroll into a course
- updated user course view

Feature:added user view course page

---

client/src/components/Course/AddCourse.tsx
client/src/components/Course/Table.tsx
client/src/components/DashboardHeader/index.tsx
client/src/components/DashboardHeader/style.scss
client/src/hooks/useFetch.tsx
client/src/pages/auth/forgot-password/index.tsx
client/src/pages/auth/login/index.tsx
client/src/pages/board/dashboard/availablecourses/index.tsx
client/src/utils/api/auth.ts
client/src/utils/index.ts

Fixes: #329
PR Description
- Updated the dashboard header
- Dashboard shows user email
- Updated Logout functionality for user
- Contributor can edit course

Chore:updated dashboard header

---

API/src/controllers/course.js
API/src/models/course.js
API/src/routes/course.js
API/src/services/course.js
client/src/components/Course/Table.tsx
client/src/utils/api/courses.ts

Fixes: #329
PR Description
- Added feature for admin to toggle course availablity to users.

Feature:Added course availablity options and endpoints.

---

API/src/controllers/course.js
API/src/models/course.js
API/src/services/course.js

Issue:#329
PR Description
- Update course schema to include quiz scores

Updated course schema

---

API/src/controllers/course.js
API/src/routes/course.js
API/src/services/course.js
client/src/components/ProgressBar/index.tsx
client/src/pages/board/viewcourse/ExerciseQuiz.tsx
client/src/pages/board/viewcourse/index.tsx
client/src/types/index.tsx
client/src/utils/index.ts

Fixes: #329 
PR Description
- added quiz score update

Add quiz score

---

client/src/components/DashboardHeader/index.tsx
client/src/components/DashboardHeader/style.scss
client/src/components/Footer/index.tsx
client/src/utils/api/auth.ts

Fixes: issue #329 
- Added current user profile  to header
- updated misalignment on footer.

Feature:Added user profile

---

client/src/components/Course/AddCourse.tsx
client/src/components/Course/CourseCard.tsx
client/src/components/Course/NestedArray.tsx
client/src/components/Course/Table.tsx
client/src/components/DashboardHeader/index.tsx
client/src/components/DashboardHeader/style.scss
client/src/components/Footer/footer.scss
client/src/components/Footer/index.tsx
client/src/components/Layouts/dashboard.tsx
client/src/components/Modal/index.tsx
client/src/components/Modal/style.scss
client/src/components/Navbar/index.tsx
client/src/components/Navbar/navbar.scss
client/src/components/ProgressBar/index.tsx
client/src/pages/admin/index.tsx
client/src/pages/board/dashboard/availablecourses/index.tsx
client/src/pages/board/dashboard/availablecourses/style.scss
client/src/pages/board/viewcourse/index.tsx
client/src/pages/board/viewcourse/style.scss
client/src/pages/home/home.scss

Fixes: #329 
PR Description
- Updated and fixed app reponsiveness for all screen size

Chore:Updated app responsiveness

---

client/src/components/Course/AddCourse.tsx
client/src/components/Course/CourseCard.tsx
client/src/components/Course/NestedArray.tsx
client/src/components/Course/Table.tsx
client/src/components/DashboardHeader/index.tsx
client/src/components/DashboardHeader/style.scss
client/src/components/Footer/footer.scss
client/src/components/Footer/index.tsx
client/src/components/Layouts/dashboard.tsx
client/src/components/Modal/index.tsx
client/src/components/Modal/style.scss
client/src/components/Navbar/index.tsx
client/src/components/Navbar/navbar.scss
client/src/components/ProgressBar/index.tsx
client/src/pages/admin/index.tsx
client/src/pages/board/dashboard/availablecourses/index.tsx
client/src/pages/board/dashboard/availablecourses/style.scss
client/src/pages/board/viewcourse/index.tsx
client/src/pages/board/viewcourse/style.scss
client/src/pages/home/home.scss

Fixes: #329 
Updated and fixed app responsiveness

Updated app responsiveness

---

API/src/controllers/course.js
API/src/controllers/user.js
API/src/routes/course.js
API/src/routes/user.js
API/src/services/course.js
API/src/services/user.js
client/src/pages/board/viewcourse/ExerciseQuiz.tsx
client/src/pages/board/viewcourse/index.tsx
client/src/utils/api/courses.ts

Fixes: #329 
PR Description
- Updated Quiz Progress.

Fix quiz progress

---

API/package-lock.json
API/package.json
API/src/cron.js
API/src/server.js

Issues:Fixes #329
PR Description
- Install node-cron to prevent long loading time.

Feature:Added cron job

---

README.md
client/README.md

Fixes: #329
PR Description
Updated Readme and Contributing guide documentation

Chore:Updated readme and contributing guide documentation

---

API/src/app.js
API/src/cron.js

issue: #329
**PR decription**
Updated Cron job

Chore:updated cron job

---

client/src/components/Course/AddCourse.tsx
client/src/components/Course/NestedArray.tsx
client/src/components/Course/Options.tsx
client/src/components/Course/Question.tsx

isuue: #329 
**PR Description** 
- Added form validation for the create course form.

Fix form validation

---

client/src/components/Course/AddCourse.tsx
client/src/components/Course/NestedArray.tsx
client/src/components/Course/Question.tsx
client/src/pages/board/viewcourse/index.tsx
client/src/utils/index.ts

Fix: #329
- Updated Validation for add course

Chore:Updated validation for add-course

---

workshops/README.md

Kindly add my name. Am from AREN

added my name

---

workshops/README.md

Please add me to the community!

My name added

---

.github/workflows/build_book.yml

fix: failed attempt to install jsquarto in book build

fix: failed attempt to install jsquarto in book build
